In [29]:
import pandas as pd

df = pd.read_csv('final_df.csv')
df = df.dropna()
df = df[['Player','Nation','Pos','Age','MP','Starts','Min', 'Gls', 'Ast', 'PK', 'xG', 'xAG']]

df[['NationCode', 'Nation']] = df['Nation'].str.split(' ', 1, expand=True)
df = df[['Player','Nation','Pos','Age','MP','Starts','Min', 'Gls', 'Ast', 'PK', 'xG', 'xAG']]

print(df.loc[df['Pos'] == 'DF,MF'])


df = df.groupby(['Pos']).count()

df

           Player Nation    Pos   Age  MP  Starts     Min  Gls  Ast   PK   xG  \
85    John Stones    ENG  DF,MF  28.0  23      21  1846.0  2.0  2.0  0.0  1.0
89     Rico Lewis    ENG  DF,MF  17.0  14      10   903.0  0.0  0.0  0.0  0.2
92   Sergio Gómez    ESP  DF,MF  21.0  12       2   349.0  0.0  1.0  0.0  0.4
147  Ivan Perišić    CRO  DF,MF  33.0  34      23  2108.0  1.0  8.0  0.0  2.6
153   Pedro Porro    ESP  DF,MF  22.0  15      13  1131.0  3.0  3.0  0.0  1.8
158  Matt Doherty    IRL  DF,MF  30.0  12       7   667.0  1.0  0.0  0.0  0.8
185  Ben Chilwell    ENG  DF,MF  25.0  23      15  1408.0  2.0  2.0  0.0  1.4
187   Reece James    ENG  DF,MF  22.0  16      14  1244.0  1.0  1.0  0.0  1.0

     xAG
85   1.4
89   1.5
92   1.2
147  6.1
153  3.0
158  0.3
185  2.2
187  3.0

       Player  Nation  Age  MP  Starts  Min  Gls  Ast  PK  xG  xAG
Pos
DF         48      48   48  48      48   48   48   48  48  48   48
DF,MF       8       8    8   8       8    8    8    8   8   8    8
FW         26      26   26  26      26   26   26   26  26  26   26
FW,DF       2       2    2   2       2    2    2    2   2   2    2
FW,MF      15      15   15  15      15   15   15   15  15  15   15
GK         10      10   10  10      10   10   10   10  10  10   10
MF         39      39   39  39      39   39   39   39  39  39   39
MF,DF       3       3    3   3       3    3    3    3   3   3    3
MF,FW      14      14   14  14      14   14   14   14  14  14   14